name: learn_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2


  pedometer: ^4.0.0
  permission_handler: ^11.0.0
  confetti: ^0.7.0

  flutter_secure_storage: 9.2.4 
  jwt_decoder: ^2.0.1 
  

  http: 1.5.0
  shared_preferences: ^2.5.3 #Almacenar datos (token)
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
